learning about exit status

diff --git a/test_file b/test_file
--- a/test_file
+++ b/test_file
@@ -1,13 +1,35 @@
-!#/bin/bash
+#!/bin/bash
 
 # Evaluate the status of a file
 
-FILE=~/.bashrc
+FILE=~/.bash_profile
 
 # -e return true if file exists
 if [ -e "$FILE" ]; then
-    # -f returns true if file exists and it is a regular file
+    # -f true if file exists and is regular file
     if [ -f "$FILE" ]; then
         echo "$FILE is a regular file"
     fi
-fi
+    # -d true if file exists and is directory
+    if [ -d "$FILE" ]; then
+        echo "$FILE is a directory"
+    fi
+    # -r true if exists and user has read permissions
+    if [ -r "$FILE" ]; then
+        echo "$FILE is readable"
+    fi
+    # -w true if exists and user had write permissions
+    if [ -w "$FILE" ]; then
+        echo "$FILE is writeable"
+    fi
+    # -x true if exists and user can execute
+    if [ -x "$FILE" ]; then
+        echo "$FILE is executable"
+    fi
+else
+    echo "$FILE does not exist"
+    # specify exit code to communicate failure
+    exit 1
+fi 
+
+exit
